// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARCIbF5vBF3mTYb6_gjK6YwlNVmtVI8OQ',
    appId: '1:846292338804:web:18126efdd6f6cceedaa921',
    messagingSenderId: '846292338804',
    projectId: 'relaq-ai',
    authDomain: 'relaq-ai.firebaseapp.com',
    storageBucket: 'relaq-ai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAPul4fn1XAsnDJkq3knEJ--TJM4WIzYo',
    appId: '1:846292338804:android:351a45351ff5abf4daa921',
    messagingSenderId: '846292338804',
    projectId: 'relaq-ai',
    storageBucket: 'relaq-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFd1Fv2WfA7NZufm93CzwLeyd4Ng5yATk',
    appId: '1:846292338804:ios:39d5e40f60485787daa921',
    messagingSenderId: '846292338804',
    projectId: 'relaq-ai',
    storageBucket: 'relaq-ai.appspot.com',
    iosBundleId: 'com.example.relaqAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFd1Fv2WfA7NZufm93CzwLeyd4Ng5yATk',
    appId: '1:846292338804:ios:ce697ae1b3d05d98daa921',
    messagingSenderId: '846292338804',
    projectId: 'relaq-ai',
    storageBucket: 'relaq-ai.appspot.com',
    iosBundleId: 'com.example.relaqAi.RunnerTests',
  );
}
